### ISSUE TITLE
Adding YRAL deeplinks for running influencer campaigns on Twitter

### ISSUE THREAD

**Issue by harshita-srivastava-yral** [yral-dapp/hot-or-not-web-leptos-ssr#309]
Objective: Marketing team would want to run a twitter campaign for promoting HON game via influencers

Requirements:

- We would require 6 different deep links to be created which should take user to the YRAL landing page.
- We should name the links with Campaign 1, Campaign 2, Campaign 3 etc till Campaign 6 at the end of the link for distinguishing them
- We should have instrumentation to attribute the number of visits on the YRAL app via the links of respective users
- There should be no expiry of these link and we should be able to use these links in future as well
- Landing page should be home feed

**Comment by Natasha-GB** [comment]
Use GA - https://support.google.com/analytics/answer/10917952?hl=en#zippy=%2Cin-this-article

**Comment by Veercodeprog** [comment]
This pull request adds and tracks the following YRAL deeplinks, with visit data being recorded and available in Google Analytics: [#319](https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/pull/319).

**Links Created:**
- **Campaign 1:** [https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign1&utm_content=hon_game](https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign1&utm_content=hon_game)
- **Campaign 2:** [https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign2&utm_content=hon_game](https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign2&utm_content=hon_game)
- **Campaign 3:** [https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign3&utm_content=hon_game](https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign3&utm_content=hon_game)
- **Campaign 4:** [https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign4&utm_content=hon_game](https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign4&utm_content=hon_game)
- **Campaign 5:** [https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign5&utm_content=hon_game](https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign5&utm_content=hon_game)
- **Campaign 6:** [https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign6&utm_content=hon_game](https://yral.com/?utm_source=twitter&utm_medium=social&utm_campaign=campaign6&utm_content=hon_game)
