### ISSUE TITLE
Creator DAO UX Bugs (Post Prod)

### ISSUE THREAD

**Issue by harshita-srivastava-yral** [yral-dapp/hot-or-not-web-leptos-ssr#415]
- [x] #422
- [x] #428
- [x] Loader to show tokens are still minting (On the wallet page and Token details page)
- [x] #430
- [x] #427

**Comment by harshitasrivastav28** [comment]
@harshitasrivastav28 To list the Use cases and behaviour of back button

**Comment by harshita-srivastava-yral** [comment]
Closing this issue as I see all the sub-issues in this task are already done. I am unable to find the PRs attached to the issues hence couldn't confirm.
