### ISSUE TITLE
Replicate Pump.fun landing page UI

### ISSUE THREAD

**Issue by harshita-srivastava-yral** [yral-dapp/hot-or-not-web-leptos-ssr#417]
We will need to replicate the pump.fun UX on icpump.fun
Key features to be supported:

- [x]  New tokens being created
- [x] Create Token CTA
- [x] List of all tokens with the "Create by", "Description" Logo etc as in pump.fun
- [x] Add twitter, discord and telegram handles for users to share the link

**Comment by harshitasrivastav28** [comment]
- Discussion on how to fetch the new tokens getting created, via big query the initial load won't be fast. From that perspective, we can make intermediate que for showing new token created.
- For every subnet we will have canister pushing all the events (cloud log in). Having 1 single cansiter the throughput might not be supported and there will be high dependency on 1 subnet.
- Cross subnet update call is not that efficient hence we would want 1 canister per subnet 
- Check if we can use firebase in our FE @ravibazz 
- @ravibazz To check if we can do 1 canister 
- We can do pagenated query completely from firebase
- @komal-rs We can use firestore DB for storing

**Comment by harshitasrivastav28** [comment]
- For lsiting we are using the server function. For realtime, @komal-rs to sit with @rupansh to update the UI

**Comment by harshitasrivastav28** [comment]
- Backend is closed. Firebase bindings is broken and we are looking at leptos
- Try in node app once and embed credential to check if its working
