### ISSUE TITLE
UI Improvement in icpump landing page

### ISSUE THREAD

**Issue by harshita-srivastava-yral** [yral-dapp/hot-or-not-web-leptos-ssr#458]
We will be further improving the landing page:

- [ ] The creation time and the principal overlap if description too much. Should fix. Maybe truncate description beyond a certain size

- [ ] Shall we make the vertical spacing uniform between the socials and Create meme coin CTA?

**Comment by harshbaz** [comment]
Fixed in: https://github.com/yral-dapp/hot-or-not-web-leptos-ssr/pull/473
