### ISSUE TITLE
Add search on landing page FE

### ISSUE THREAD

**Issue by harshita-srivastava-yral** [yral-dapp/hot-or-not-web-leptos-ssr#461]

**Comment by harshita-srivastava-yral** [comment]
-Integration is done
- ML feed API is not authenticated yet.
- Search API need not be authenticated. 
- Calling to big query should  be authenticated and should not be public query.

**Comment by harshbaz** [comment]
Design prototype here:
https://stackblitz.com/edit/sveltejs-kit-template-default-vaunbr
